enum Actions {
  LOGIN = "login",
  LOGOUT = "logout",
  SIGN_UP = "signUp",
  GET_APPLICATION = "getApplication",
  GET_DEVICE = "getDevice",
  GET_MODULE = "getModule",
  GET_APPLICATIONS = "getApplications",
  GET_DEVICES = "getDevices",
  GET_MODULES = "getModules",
  GET_COMMANDS = "getCommands",
  CREATE_APPLICATION = "createApplication",
  CREATE_DEVICE = "createDevice",
  CREATE_MODULE = "createModule",
  CREATE_COMMAND = "createCommand",
  DELETE_APPLICATION = "deleteApplication",
  DELETE_DEVICE = "deleteDevice",
  DELETE_MODULE = "deleteModule",
  DELETE_COMMAND = "deleteCommand",
  UPDATE_LOCALE = "updateLocale",
  UPDATE_BREADCRUMB = "updateBreadcrumb",
  UPDATE_LAYOUT = "updateLayout",
  UPDATE_REGISTER_DATA = "updateRegisterData",
  UPDATE_STEP_1_REGISTER_DATA = "updateStep1RegisterData",
  UPDATE_STEP_2_REGISTER_DATA = "updateStep2RegisterData",
  UPDATE_STEP_3_REGISTER_DATA = "updateStep3RegisterData",
  UPDATE_APPLICATIONS = "updateApplications",
  UPDATE_DEVICES = "updateDevices",
  UPDATE_MODULES = "updateModules",
  UPDATE_COMMANDS = "updateCommands",
  EXECUTE_COMMAND = "executeCommand",
}

enum Mutations {
  SET_CREDENTIALS = "setCredentials",
  SET_TOKEN = "setToken",
  SET_LOCALE = "setLocale",
  SET_BREADCRUMB = "setBreadcrumb",
  SET_LAYOUT = "setLayout",
  SET_REGISTER_DATA = "setRegisterData",
  SET_STEP_1_REGISTER_DATA = "setStep1RegisterData",
  SET_STEP_2_REGISTER_DATA = "setStep2RegisterData",
  SET_STEP_3_REGISTER_DATA = "setStep3RegisterData",
  SET_APPLICATIONS = "setApplications",
  SET_DEVICES = "setDevices",
  SET_MODULES = "setModules",
  SET_COMMANDS = "setCommands",
  REMOVE_TOKEN = "removeToken",
  REMOVE_CREDENTIALS = "removeCredentials",
}

export { Actions, Mutations };
